### ISSUE TITLE
.cakeに記載するパス情報は絶対パスでも相対パスでもよい

### ISSUE THREAD

**Issue by k1LoW** [dotcake/dotcake#1]
2014/04/28時点で、cake.vimが対応している`.cake`のパス情報は絶対パスのみとなっているかと思いますが、
- `.cake`は将来的にプロジェクトで共有されるものになると予想
- 各開発者でプロジェクトルートが違う可能性がある

という2点から
- `.cake`に記載するパス情報は絶対パスでも相対パスでも良い

という`.cake`仕様を提案したいと思います。

(よさげなら「ok」でもLGTM画像でも貼ってください)

(「各エディタ拡張が両方に対応すべき」というものではありません)

**Comment by violetyk** [comment]
初Issue :cake:  よろしくおねがいします！
- `.cake`に記載するパス情報は絶対パスでも相対パスでも良い

OKです :ok_woman:　確かにプロジェクトルートは違う可能性がありますね。

**Comment by junichi11** [comment]
OKです :ok_hand:

**Comment by k1LoW** [comment]
それではこちらは採用ということでCloseします。
