### ISSUE TITLE
dotcakeのバージョニングについて

### ISSUE THREAD

**Issue by k1LoW** [dotcake/dotcake#10]
お久しぶりです。

そろそろCakePHP3が出そうですね。。。

その前に dotcake にバージョンをつけて明確にCakePHP3対応版とは分ける形にしたほうがいいですね。
1. 2.0.0からつける (CakePHPのメジャーバージョンに合わせる)
2. 1.0.0からつける
3. 2.5.5からつける 

など。
その他アイデアなどありましたら是非。

**Comment by junichi11** [comment]
対応がわかりやすいので、1がよさそうかなと思います。

**Comment by k1LoW** [comment]
> 対応がわかりやすい

確かに、気楽にバージョン付けれそうですね。

余談ですが、Rubyは今2.1.4ですが、2.1.x の x の部分に「2桁をつけたくない」という思いがあるらしく、「残り6つだー」と不安要素になっているらしいですw

**Comment by k1LoW** [comment]
それでは、1で行こうかなと思います
