### ISSUE TITLE
.cakeに記載するパス情報にはapp/Model/等のデフォルトのパスもあってよい

### ISSUE THREAD

**Issue by k1LoW** [dotcake/dotcake#2]
これは個人的(cake2.el的)には修正の必要があるのですが、、、、
- CakePHP2においてApp::build()を純粋に出力するとデフォルトのパスも入る
- 将来的に`.cake`に完全に頼ったエディタ拡張がでる可能性がある
  - `.cake`があれば、それしか使わないなど

という点から、「`.cake`のパス情報にはデフォルトパスがあってもよい」としたほうが健全かな、と。

如何でしょう？

**Comment by junichi11** [comment]
> CakePHP2においてApp::build()を純粋に出力するとデフォルトのパスも入る

Dotcake pluginで`.cake`をつくったときに含まれる`"models":[".\/Model\/"]`等があってもよいということですよね？ OKです。

**Comment by violetyk** [comment]
僕もオッケーです！あと、指定するパスのリストは、優先する順番がよいです！

**Comment by k1LoW** [comment]
デフォルトパス情報があってもよいかについては、採用ということでCloseします。
@violetyk さんのパスリストの優先度については #4 に切り分けてみました！
