### ISSUE TITLE
.cakeに記載するパス情報はプロジェクトにおける優先度が高いほうを先に書くことが望ましいとする

### ISSUE THREAD

**Issue by k1LoW** [dotcake/dotcake#4]
`.cake`に記載するパス情報はプロジェクトにおける優先度が高いほうを先に書くことを前提としてエディタ拡張が利用することがある。
よって、

> App::build()等で指定したパス(例：`/path/to/extra/Model/`が`app/Model/`といったデフォルトパスよりも先に書くことが望ましい

とする。

**Comment by k1LoW** [comment]
@violetyk こんな感じですかね？

**Comment by violetyk** [comment]
ですです！ありがとうございます :laughing:

**Comment by k1LoW** [comment]
:+1: 

あくまで「エディタ拡張のために推奨」だと思っています。
なので、対応としては、
- `.cake`の仕様説明のページができれば推奨事項として記載する
  - 何が優先なのかはプロジェクト次第なので
- Dotcakeでは「デフォルトパスを常に後ろにする」という実装にする
  - デフォルトパスは大抵後から追加されたパスより優先度が低い場合が多いので

でいいかと思っています。

**Comment by junichi11** [comment]
:+1:

**Comment by k1LoW** [comment]
#6 がマージされたらこちらはCloseしますね

**Comment by violetyk** [comment]
:+1:

**Comment by k1LoW** [comment]
MergeをさせてもらったのでこちらもCloseしますー
