### ISSUE TITLE
Coding Standards

### ISSUE THREAD

**Issue by junichi11** [dotcake/dotcake#7]
何か基準があった方がよいと思うのですが、コーディング規約は、どうしましょうか？
- 現在のソースコードに合わせる
- CakePHPのコーディング規約等に合わせる

**Comment by k1LoW** [comment]
確かにあったほうがいいですねー。
決まったら`.editorconfig`を置きましょうか。

個人的好みは今のままなのですが、「今のまま」はあまりに個人的すぎるので
- PSR-1準拠
- CakePHP準拠

のどちらかの選択肢で決めたほうがよさそうな気がします。
で、CakePHP準拠に1票です。

**Comment by junichi11** [comment]
> 決まったら.editorconfigを置きましょうか。

あったほうがよさそうですね、お願いします。

> 個人的好みは今のままなのですが、「今のまま」はあまりに個人的すぎるので
> - PSR-1準拠
> - CakePHP準拠
> 
> のどちらかの選択肢で決めたほうがよさそうな気がします。

私もCakePHP準拠に１票です。

**Comment by violetyk** [comment]
CakePHP準拠ですとコーディング規約はこの辺のですかね？

コーディング規約 — CakePHP Cookbook 2.x ドキュメント http://book.cakephp.org/2.0/ja/contributing/cakephp-coding-conventions.html

了解です！

**Comment by k1LoW** [comment]
CakePHP準拠で　ということで #8 で実際の修正を進行しています

**Comment by junichi11** [comment]
了解しました。ありがとうございます！

**Comment by k1LoW** [comment]
というわけで、 #8 でDotcakeに規約を適用した時点でこちらもCloseします
